### PR TITLE
[Tests-Only] enforce strict type checking in acceptace tests code

### PR DESCRIPTION
**Pull request by dpakach**
Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code

**note** this PR was generated by a automated script

### CODE REVIEW

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiTestingApp-master-mariadb10.2-php7.3</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/testing/1686/13/1

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiTestingApp-master-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/testing/1687/14/1

**Comment by individual-it** [comment]
ci failed in one clone step, restarting

**Review by individual-it — APPROVED** [review]

**Comment by ownclouders** [comment]
:boom: Acceptance tests pipeline <strong>apiTestingApp-master-mariadb10.2-php7.4</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/testing/1688/14/1

**Comment by individual-it** [comment]
grafik

**Review by phil-davis — APPROVED** [review]

**Pull request merged**
