### PR TITLE
Renamed test1 to user1 for notifications app acceptance tests

### PR DESCRIPTION
**Pull request by Julian1998**
## Description

Renamed test1 to user1 for notifications app acceptance tests

## Checklist:

- [x] Latest changes are published according to [instructions in README.md](https://github.com/owncloud/testing#publish-latest-version-as-github-release)

### CODE REVIEW

**Comment by individual-it** [comment]
why is this needed?

**Comment by Julian1998** [comment]
@individual-it Woups forgot about that part ;)
https://github.com/owncloud/phoenix/pull/1205
The notifications acceptance test want the username to be test1... but in Phoenix we work with user1... are there any better solutions?

**Comment by individual-it** [comment]
@Julian1998 here `test1` is just the default for the case when no username is send. In you tests you should send the correct user in the `user` parameter

**Comment by Julian1998** [comment]
> @Julian1998 here `test1` is just the default for the case when no username is send. In you tests you should send the correct user in the `user` parameter

Alright! Will do that! Thx :)

**Pull request closed without merging**
